namespace KibernumCrud.IntegrationTests.Configuration;

[CollectionDefinition(nameof(IntegrationTestsKibernumCollectionFixture))]
public class IntegrationTestsKibernumCollectionFixture : ICollectionFixture<KibernumApiFactory>;